config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "dashboard/index"

  resource :session
  resources :passwords, param: :token
  resources :logs
  resources :artists

  resources :records do
    collection do
      get :search
      get :discogs_search
      get :discogs_results
      get :results
      post "import/:id", to: "records#discogs_import", as: :import
    end
  end

  post "dashboard/log"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @records_count = Record.all.count
    @artists_count = Artist.all.count
    @logs_count = Log.all.count
    @last_played = Log.order(date: :desc, created_at: :desc).first
    @total_time_listened = Log.joins(:record).sum(:running_time)

    @artists = Artist.joins(:records).group(:name).order("count(records.id) desc").limit(5)
  end

  def log
    @last_played = Log.new
    @last_played.record_id = params[:record_id]
    @last_played.date = Date.today
    @last_played.save

    @logs_count = Log.all.count
    @total_time_listened = Log.joins(:record).sum(:running_time)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to logs_path }
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def format_time(time)
    days = time / 86400
    hours = (time % 86400) / 3600
    minutes = (time % 3600) / 60
    "#{days} day#{days > 1 || days == 0 ? "s" : ""} #{hours} hour#{hours > 1 || hours == 0 ? "s" : ""} #{minutes} minute#{minutes > 1 || minutes == 0 ? "s" : ""}  "
  end
end

app/views/dashboard/_last_played.html.erb
<div id="last_played" class="w-full max-w-sm">
  <h2 class="mb-4 text-2xl font-bold">Recently played</h2>
  <% if @last_played.present? %>
    <div class="mb-2 overflow-hidden bg-black rounded-lg aspect-square">
      <%= image_tag @last_played.record.cover, class: "w-full h-full object-cover" if @last_played.record.cover.present? %>
    </div>
    <div class="">
      <p><%= @last_played.record.title %></p>
      <p class="text-gray-400"><%= @last_played.record.artist.name %></p>
    </div>
  <% end %>
</div>

app/views/dashboard/_log_box.html.erb
<div id="log_box" class="relative">
  <%= form_with(url: search_records_path, method: :get, local: true, class: "mb-4", data: {controller: "form", turbo_frame: "records_results" }) do |f| %>
    <div class="input-group">
      <%= f.text_field :query, class: "form-control text-black p-2 rounded max-w-2xl w-full", placeholder: "Search by artist or album...", data: {action: "input->form#submit"},  autocomplete: "off" %>
    </div>
  <% end %>
  <div class="absolute w-full p-4 bg-gray-950 top-[calc(100%_+_1rem)]">
  <%= turbo_frame_tag :records_results do %>
    <p class="text-gray-300">Start typing to search for the record</p>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<h1 class="text-4xl font-bold sr-only">Dashboard</h1>
<div class="flex items-center justify-between gap-8 my-24">
  <div>
    <p class="mb-8 text-2xl text-center text-gray-300 lg:leading-loose lg:text-5xl">Your collection has
      <span class="font-bold text-white">
        <span id="records_count"><%= @records_count %></span>
        unique records.</span>
      <br/>
      This year, you've played records 
      <span class="font-bold text-gray-200">
        <span id="logs_count"><%= @logs_count %></span>
        times</span>, 
      <br/>
      spending a total of  <br/>
      <span class="font-bold text-gray-200">
        <span id="total_time_count"><%= format_time(@total_time_listened) %></span>
      </span>listening.</p>
  </div>
  <%= render "last_played"%>
</div>
<section class="my-24">
  <h2 class="mt-8 mb-4 text-2xl font-bold">Log</h2>
  <%= render "log_box" %>
</section>
</div>
<section>
  <h2 class="mt-8 mb-4 text-2xl font-bold">Artists</h2>
  <div class="grid grid-cols-5 gap-4">
    <% @artists.each do |artist| %>
      <%= link_to artist_path artist do %>
        <div class="p-1 text-black bg-gray-200 rounded-2xl">
          <div class="overflow-hidden rounded-xl aspect-[4/5]">
            <% if artist.avatar.attached? %>
              <%= image_tag artist.avatar.variant(format: :avif, resize_to_fill: [300, 300]), class: "object-cover size-full" %>
            <%end%>
          </div>
          <div class="p-2">
            <h3 class="text-xl font-bold"><%= artist.name %></h3>
            <p><%= artist.records.count %> <%= "record".pluralize(artist.records.count) %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/dashboard/log.turbo_stream.erb
<%= turbo_stream.update "last_played" do %>
  <%= render partial: 'dashboard/last_played' %>
<% end %>
<%= turbo_stream.update "log_box" do %>
  <%= render partial: 'dashboard/log_box' %>
<% end %>
<%= turbo_stream.update "total_time_count" do %>
  <%= format_time(@total_time_listened)%>
<% end %>
<%= turbo_stream.update "logs_count" do %>
  <%= @logs_count %>
<% end %>