config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "dashboard/index"

  resource :session
  resources :passwords, param: :token
  resources :logs
  resources :artists

  resources :records do
    collection do
      get :search
      get :discogs_search
      get :discogs_results
      get :results
      post "import/:id", to: "records#discogs_import", as: :import
    end
  end

  post "dashboard/log"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_one_attached :avatar
  has_many :records, dependent: :destroy
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all.order(name: :asc)
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end


  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)
    redirect_to artists_path
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :avatar)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit.html.erb
<div>
  <h1 class="mb-12 text-4xl font-bold">Edit artist</h1>

  <%= form_with model: @artist, class: "flex flex-col gap-4" do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class: "p-2 rounded-md text-black" %>

    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "p-2 rounded-md text-black" %>

    <%= form.submit %>
  <% end %>
</div>

app/views/artists/index.html.erb
<header class="flex items-center justify-between my-8">
  <h1 class="text-4xl font-bold">Artists</h1>
  <%= link_to "+ New Artist", new_artist_path,  :class => "text-gray-300 hover:text-gray-100 px-2 py-1 rounded-md  flex items-center justify-center" %>
</header>
<ul class="grid grid-cols-4 gap-6">
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist_path artist do %>
        <div class="p-1 text-black bg-gray-200 rounded-2xl">
          <div class="overflow-hidden rounded-xl aspect-[4/5]">
            <% if artist.avatar.attached? %>
              <%= image_tag artist.avatar.variant(format: :avif, resize_to_fill: [300, 300]), class: "object-cover size-full" %>
            <%end%>
          </div>
          <div class="p-2">
            <h3 class="text-xl font-bold"><%= artist.name %></h3>
            <p><%= artist.records.count %> <%= "record".pluralize(artist.records.count) %></p>
          </div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<div>
  <h1 class="mb-12 text-4xl font-bold">Add new record</h1>

  <%= form_with model: @artist, class: "flex flex-col gap-4" do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class: "p-2 rounded-md text-black" %>

    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "p-2 rounded-md text-black" %>

    <%= form.submit %>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="flex items-end justify-between gap-8 mb-4 h-60">
  <h1 class="text-5xl"><%= @artist.name %></h1>
  <%= image_tag @artist.avatar, class: "h-full rounded-2xl" if @artist.avatar.present? %>
</div>
<div class="flex justify-end gap-8 mb-24">

<%= link_to "Edit", edit_artist_path(@artist), class: "text-blue-400 px-2 py-1 rounded-md" %>
<%= button_to "Delete artist", artist_path(@artist), method: :delete, class: "text-red-400 px-2 py-1 rounded-md" %>
</div>
<h2 class="my-4 text-2xl font-medium">Records</h2>
<div class="grid grid-cols-2 gap-4">
  <% @artist.records.each do |record| %>
    <%= render record%>
  <% end %>
</div>