config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "dashboard/index"

  resource :session
  resources :passwords, param: :token
  resources :logs
  resources :artists

  resources :records do
    collection do
      get :search
      get :discogs_search
      get :discogs_results
      get :results
      post "import/:id", to: "records#discogs_import", as: :import
    end
  end

  post "dashboard/log"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_header.html.erb
<header class="sticky top-0 z-10 bg-gray-950">
  <div class="container flex items-center justify-between p-4 mx-auto">
    <h1 class="text-2xl font-bold"><%= link_to "GrooveTracker", root_path %></h1>
    <ul class="flex space-x-4">
      <%# change class if active current page %>
      <li><%= link_to "Dashboard", root_path, class: "text-gray-500 hover:text-gray-200 hover:bg-black block px-2 py:1 rounded #{current_page?(root_path) ? 'bg-black' : ''}" %></li>
      <li><%= link_to "Records", records_path, class: "text-gray-500 hover:text-gray-200 hover:bg-black block px-2 py:1 rounded #{current_page?(records_path) ? 'bg-black' : ''}"  %></li>
      <li><%= link_to "Logs", logs_path, class: "text-gray-500 hover:text-gray-200 hover:bg-black block px-2 py:1 rounded #{current_page?(logs_path) ? 'bg-black' : ''}"  %></li>
      <li><%= link_to "Artists", artists_path, class: "text-gray-500 hover:text-gray-200 hover:bg-black block px-2 py:1 rounded #{current_page?(artists_path) ? 'bg-black' : ''}"  %></li>
    </ul>
  </div>
</header>