config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get "dashboard/index"

  resource :session
  resources :passwords, param: :token
  resources :logs
  resources :artists

  resources :records do
    collection do
      get :search
      get :discogs_search
      get :discogs_results
      get :results
      post "import/:id", to: "records#discogs_import", as: :import
    end
  end

  post "dashboard/log"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/record.rb
class Record < ApplicationRecord
  has_one_attached :cover
  belongs_to :artist
  has_many :logs, dependent: :destroy

  validates :title, presence: true
end

app/controllers/records_controller.rb
require "net/http"
require "uri"

class RecordsController < ApplicationController
  def index
    @records = Record.all.order(created_at: :desc)
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      respond_to do |format|
        format.html { redirect_to records_path }
        format.turbo_stream
      end
    else
      render :new
    end
  end

  def new
    @record = Record.new
  end

  def show
    @record = Record.find(params[:id])
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    @record.update(record_params)
    redirect_to records_path
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_path }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@record) }
    end
  end

  def search
    return if params[:query].blank?

    @records = Record.joins(:artist)
                  .where("LOWER(records.title) LIKE :query OR LOWER(artists.name) LIKE :query",
                    query: "%#{params[:query].downcase}%").limit(6)
  end

  def discogs_search
  end

  def discogs_results
    uri = URI("https://api.discogs.com/database/search")
    uri.query = URI.encode_www_form({
      q: params[:query],
      type: "release"
    })

    request = Net::HTTP::Get.new(uri)
    request["Authorization"] = "Discogs token=#{ENV['DISCOGS_TOKEN']}"

    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(request)
    end

    @results = JSON.parse(response.body)["results"]
  end

  def discogs_import
    uri = URI("https://api.discogs.com/releases/#{params[:id]}")

    request = Net::HTTP::Get.new(uri)
    request["Authorization"] = "Discogs token=#{ENV['DISCOGS_TOKEN']}"

    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(request)
    end

    @discogs_record = JSON.parse(response.body)

    @record = Record.find_by(discogs_id: @discogs_record["id"])

    if @record.nil?

    @artist = Artist.find_by(discogs_id: @discogs_record["artists"][0]["id"])
    if @artist.nil?
      uri = URI("https://api.discogs.com/artists/#{@discogs_record["artists"][0]["id"]}")
      request = Net::HTTP::Get.new(uri)
      request["Authorization"] = "Discogs token=#{ENV['DISCOGS_TOKEN']}"
      response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
        http.request(request)
      end
      @discogs_artist = JSON.parse(response.body)
      @artist = Artist.create(name: @discogs_artist["name"], discogs_id: @discogs_artist["id"])

      if @discogs_artist["images"].present? && @discogs_artist["images"][0].present?
        avatar_uri = URI(@discogs_artist["images"][0]["uri"])
        avatar_response = Net::HTTP.get_response(avatar_uri)
        avatar_file = StringIO.new(avatar_response.body)

        @artist.avatar.attach(io: avatar_file, filename: "avatar.jpg")
      end

      @artist.save
    end

    @running_time = @discogs_record["tracklist"].map do |track|
      if track["duration"].present?
        minutes, seconds = track["duration"].split(":").map(&:to_i)
        minutes * 60 + seconds
      else
        0
      end
    end.sum

    @record = Record.new(
      title: @discogs_record["title"],
      discogs_id: @discogs_record["id"],
      running_time: @running_time,
      artist_id: @artist.id,
    )

    cover_uri = URI(@discogs_record["images"][0]["resource_url"])
    cover_response = Net::HTTP.get_response(cover_uri)
    cover_file = StringIO.new(cover_response.body)
    @record.cover.attach(io: cover_file, filename: "cover.jpg")
    @record.save

    respond_to do |format|
      format.html { redirect_to records_path }
      format.turbo_stream
    end
    end
  end


  private

  def record_params
    params.require(:record).permit(:title, :artist_id, :cover, :running_time)
  end
end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/records/_discogs_result.html.erb
<li class="relative">
<turbo-frame>
  <%= button_to import_records_path(result["id"]), class: "flex gap-4 text-left w-full hover:bg-gray-900 hover:text-gray-200 rounded-xl overflow-hidden px-2 py-2 mx-4" do %>
    <div class="overflow-hidden bg-black rounded-md size-20">
      <img class="block object-cover size-full" src="<%= result["cover_image"] %>" alt="<%= result["title"] %>">
    </div>
    <div>
      <span class="block text-lg font-bold"><%= result["title"] %></span>
      <span class="block text-sm text-gray-400"><%= result["year"] %></span>
      <ul class="flex gap-2">
        <% result["format"].each do |format| %>
          <li class="block text-sm text-gray-400"><%= format %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</turbo-frame>
  <span class="[[busy]~&]:block hidden absolute top-1/2 right-[5rem] transform -translate-x-1/2 -translate-y-1/2">
    <svg class="w-6 h-6 text-white animate-spin" fill="none" viewBox="0 0 24 24">
      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
      <path class="opacity-75" d="M12 6v6m0 0v6m0-6h6m-6 0H6" stroke="currentColor" stroke-width="4"></path>
    </svg>
  </span>
</li>

app/views/records/_record.html.erb
<%= turbo_frame_tag "record_#{record.id}", class:"h-full" do %>
  <div class="relative">
    <%= link_to  record_path(record), class: "flex hover:bg-gray-800  h-full items-start gap-4 p-3 rounded-md border-gray-800 border" do %>
      <div class="overflow-hidden bg-black rounded-md size-24 shrink-0">
        <%= image_tag record.cover, class: "size-full object-contain" if record.cover.present? %>
      </div>
      <div>
        <p class="w-full pr-16 overflow-hidden font-medium text-white text-ellipsis"><%= record.title %></p>
        <span class="text-xs text-gray-300"><%= record.artist.name %></span><br/>
        <span class="text-sm text-gray-400">Played <span class="text-gray-300"> <%= record.logs.count %> <%= "time".pluralize(record.logs.count) %></span></span><br/>
        <% if record.logs.last.present? %>
          <span class="text-sm text-gray-400">Last played <span class="text-gray-300"><%= record.logs.last.date.strftime("%m/%d/%Y") %></span></span>
        <% else %>
          <span class="text-sm text-gray-400">Never played yet</span>
        <% end %>
      </div>
    <% end %>
    <%= button_to  logs_path, params: { record_id: record.id, source: "records_list" }, method: :post, class: "bg-transparent opacity-75 hover:opacity-100  text-black  rounded-md absolute top-4 right-4" do %>
      <%= image_tag  "play.svg", class:"size-6" %>
    <% end %>
  </div>
<% end %>

app/views/records/_result.html.erb
         
<li class="flex gap-6">
  <%= button_to import_records_path(result["id"]) do %>
    <img class="block w-24 shrink-0" src="<%= result["cover_image"] %>" alt="<%= result["title"] %>">
    <div>
      <span class="block text-lg font-bold"><%= result["title"] %></span>
      <span class="block text-sm text-gray-500"><%= result["year"] %></span>
      <ul class="flex gap-2">
        <% result["format"].each do |format| %>
          <li class="block text-sm text-gray-500"><%= format %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</li>

app/views/records/create.turbo_stream.erb
<%= turbo_stream.prepend "records" do %>
    <%= render partial: "records/record", locals: {record: @record} %>
<% end %>
<%= turbo_stream.update "modal" "" %>

app/views/records/discogs_import.turbo_stream.erb
<%= turbo_stream.prepend "records" do %>
    <%= render partial: "records/record", locals: {record: @record} %>
<% end %>
<%= turbo_stream.update "modal" "" %>

app/views/records/discogs_results.html.erb
<%= turbo_frame_tag :discogs_results do %>
  <% if @results.present? %>
    <ul class="space-y-2 search-results">
      <% @results.each do |result| %>
        <%= render partial: "records/discogs_result", locals: { result: result } %>
      <% end %>
    </ul>
  <% else %>
    <p class="text-white">No results found</p>
  <% end %>
<% end %>

app/views/records/discogs_search.html.erb
<div class="container" ">
  <%= turbo_frame_tag :modal do %>
    <dialog data-controller="modal"  data-action="click->modal#clickOutside"   class="fixed text-black max-w-4xl w-full inset-0 z-10 rounded-lg backdrop:backdrop-blur-md backdrop:bg-gray-800/20 max-h-[90dvh]">
      <div class="relative">
        <button data-action="click->modal#close"  class="absolute top-4 right-4">&times;</button>
        <div data-controller="discogs-search">
          <h2 class="px-6 pt-6 text-2xl font-bold">Search Discogs Database</h2>
          <div class="sticky top-0 z-10 flex gap-4 px-6 py-6 bg-white">
            <%= form_with(url: discogs_results_records_path, method: :get, local: true, data: {controller: "form", turbo_frame: "discogs_results", "discogs-search-target": "form" }, class: "max-w-sm w-full") do |f| %>
              <div class="input-group">
                <%= f.text_field :query, class: "form-control text-black p-2 border border-gray-900 rounded-md w-full", placeholder: "Search by artist or album...", data: {action: "input->form#submit", "discogs-search-target": "input"},  required: true, autocomplete: "off" %>
              </div>
            <% end %>
            <button data-action="discogs-search#scan" class="px-4 py-1 text-black bg-white border border-black rounded-md">𝄃𝄂𝄂𝄀𝄁𝄃𝄂𝄂𝄃</button>
          </div>
          <video id="video"  height="480" class="hidden w-full" autoplay data-discogs-search-target="video" playsinline> </video>
          <div class="overflow-hidden grow">
            <%= turbo_frame_tag :discogs_results, src: "/records/discogs_results" ,  class:"h-full group overflow-y-auto"  do %>
              <p class="p-6">Loading results</p>
            <% end %>
          </div>
        </div>
      </div>
    </dialog>
  <% end %>
</div>

app/views/records/edit.html.erb
<div>
  <h1 class="mb-12 text-4xl font-bold">Edit record</h1>
  <%= turbo_frame_tag "record_#{@record.id}" do %>
    <div class="p-4">
      <%= link_to records_path, class: "mb-4 block" do %>
        &larr; Back
      <% end %>
      <%= form_with model: @record, class: "flex flex-col gap-4" do |form| %>
        <%= form.label :title %>
        <%= form.text_field :title, class: "p-2 rounded-md text-black" %>
        <%= form.label :artist %>
        <%= form.select :artist_id, Artist.all.map { |artist| [artist.name, artist.id] }, { prompt: "Select artist" }, class: "p-2 rounded-md text-black" %>
        <%= form.label :running_time %>
        <%= form.number_field :running_time, class: "p-2 rounded-md text-black" %>
        <div>
          <%= image_tag @record.cover, class: "w-1/2" if @record.cover.present? %>
        </div>
        <%= form.label :cover %>
        <%= form.file_field :cover, class: "p-2 rounded-md text-black" %>
        <button type="submit" class="text-blue-400">
          Update the record
        </button>
      <% end %>
    </div>
  <% end %>
</div>

app/views/records/import.turbo_stream.erb
<%= turbo_stream.prepend "records" do %>
    <%= render partial: "records/record", locals: {record: @record} %>
<% end %>
<%= turbo_stream.update "modal" "" %>

app/views/records/index.html.erb
<%= turbo_stream_from "records" %>
<div>
  <header class="flex items-center justify-between gap-6">
    <h1 class="my-8 text-4xl font-bold text-white">My Collection</h1>
    <%= link_to new_record_path, data: { turbo_frame: "modal"},  :class => "text-gray-300 hover:text-gray-100 px-2 py-1 rounded-md  flex items-center justify-center" do %>
      + New Record</span>
  <% end %>
</header>
<div class="grid grid-cols-1 gap-8 md:grid-cols-3">
  <div class="w-full ">
    <%= link_to discogs_search_records_path, data: { turbo_frame: "modal"},  :class => "font-bold text-white px-2 py-1 rounded-md size-full  flex items-center justify-center" do %>
      <span class="text-xl text-center"><span class="text-3xl">+</span><br/>
        Import Record</span>
    <% end %>
  </div>
  <%= turbo_frame_tag :records, class: "contents" do %>
    <%= render @records %>
  <% end %>
</div>
</div>

app/views/records/new.html.erb
<div>
  <h1 class="mb-12 text-4xl font-bold">Add new record</h1>
  <%= turbo_frame_tag :modal do %>
    <dialog data-controller="modal" data-action="click->modal#clickOutside"  class="fixed inset-0 z-10 rounded-lg backdrop:backdrop-blur-md backdrop:bg-gray-800/20">
      <div class="p-6">
        <button data-action="click->modal#close" class="absolute top-4 right-4">Close</button>
        <%= form_with model: @record, class: "flex flex-col gap-4"  do |form| %>
          <% if @record.errors.any? %>
            <div class="relative px-4 py-3 text-red-700 bg-red-100 border border-red-400 rounded">
              <h2 class="font-bold"><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>
              <ul class="list-disc list-inside">
                <% @record.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <%= form.label :title %>
          <%= form.text_field :title, class: "p-2 rounded-md text-black", autofocus: true %>
          <%= form.label :artist %>
          <%= form.select :artist_id, Artist.all.map { |artist| [artist.name, artist.id] }, { prompt: "Select artist" }, class: "p-2 rounded-md text-black" %>
          <%= form.label :running_time %>
          <%= form.number_field :running_time, class: "p-2 rounded-md text-black" %>
          <%= form.label :cover %>
          <%= form.file_field :cover, class: "p-2 rounded-md text-black" %>
          <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <% end %>
      </div>
    </dialog>
  <% end %>
</div>

app/views/records/results.html.erb
<%= turbo_frame_tag :discogs_results do %>
  <% if @results.present? %>
    <ul class="space-y-4 search-results">
      <% @results.each do |result| %>
        <%= render partial: "records/result", locals: { result: result } %>
      <% end %>
    </ul>
  <% else %>
    <p class="text-white">No results found</p>
  <% end %>
<% end %>

app/views/records/search.html.erb
<%= turbo_frame_tag :records_results do %>
  <% if @records.present? %>
    <div class="grid grid-cols-6 gap-8 mt-10">
      <% @records.each do |record| %>
        <%= button_to  dashboard_log_path, params: { record_id: record.id }, method: :post, class: "w-full block text-left text-sm" do %>
      
          <div class="w-full mb-2 overflow-hidden bg-black aspect-square rounded-xl">
            <%= image_tag record.cover, class: "w-full h-full object-cover" if record.cover.present? %>
          </div>
          <p><%= record.title %></p>
          <p class="text-gray-400"><%= record.artist.name %></p>
        <% end %>
      <% end %>
    <% else %>
      <p>No records found, would you like to  
        <%= link_to "add a new one", discogs_search_records_path, data: { turbo_frame: "modal" }, class: "text-orange-500" %>?
      </p>
    <% end %>
  <% end %>

app/views/records/show.html.erb
<%= turbo_frame_tag "record_#{@record.id}" do %>
  <div class="p-2">
    <%= link_to records_path, class: "text-gray-200 block mb-2" do %>
      &larr; Back
    <%end %>
    <div class="mb-2 overflow-hidden bg-black rounded-md size-24">
      <%= image_tag @record.cover, class: "size-full object-contain" if @record.cover.present? %>
    </div>
    <p class="w-full overflow-hidden text-sm font-medium text-white text-ellipsis"><%= @record.title %></p>
    <span class="text-sm text-gray-300"><%= @record.artist.name %></span><br/>
    <div class="flex gap-4">
      <%= link_to "Edit", edit_record_path(@record), class: "text-blue-300  py-1 decoration-none" %>
      <%= button_to "Delete record", record_path(@record), method: :delete,  data: {turbo_confirm: "Are you sure?"}, class: "text-red-300  px-2 py-1" %>
    </div>
  </div>
<% end %>